---

- hosts: ubuntu_servers
  become: true
  tasks:

  - name: update apt cache
    ansible.builtin.apt:
      update_cache: true

  - name: apply pending updates
    ansible.builtin.apt:
      upgrade: dist
      
  - name: verify unattended upgrades are started and enabled
    service:
      name: unattended-upgrades
      state: started
      enabled: true
    
  - name: copy custom config file to 50unattended-upgrades file
    copy:
      src: custom_unattended_upgrades_config
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
      owner: root
      group: root
      mode: 0644
    register: upgrades_file_updated

  - name: restart unattended upgrades file if config file was changed
    service:
      name: unattended-upgrades
      state: restarted
      enabled: true
    when: upgrades_file_updated.changed

  - name: allow ssh connections to the host machine through UFW
    community.general.ufw:
      rule: allow
      port: '22'

  - name: start and enable the UFW firewall
    community.general.ufw:
      state: enabled

  - name: install QEMU guest agent for proxmox virtual machines
    ansible.builtin.apt:
      name: qemu-guest-agent
      state: latest

  - name: start and enable QEMU guest agent
    service:
      name: qemu-guest-agent
      state: started
      enabled: true